name: Api

env:
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.build }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            build:
              - 'src/backend/Applications/ScanIta.Extractor.Api/**'
  
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/tiaringhio/scanitaextractor

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/backend/Applications/ScanIta.Extractor.Api/Dockerfile
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ghcr.io/tiaringhio/scanitaextractor:latest , ghcr.io/tiaringhio/scanitaextractor:${{ github.sha }}

  deploy:
    needs: [changes, build-and-push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create new revision
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add -n containerapp
            echo "Creating new revision"
            az containerapp update -n ${{ secrets.API_NAME }} -g ${{ secrets.AZURE_RG }} --image ghcr.io/tiaringhio/scanitaextractor:${{ github.sha }}
