name: Api

env:
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.build }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            build:
              - 'src/backend/Applications/**'
  
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/scanitaextractor/api:latest
